app:
    resource: "@AppBundle/Controller/"

homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

admin:
    path:      /admin
    defaults:  { _controller: AppBundle:Default:admin }

registration:
    path: /registration
    defaults:  { _controller: AppBundle:Authentication:registration }
    methods:  [POST]
