api_employer:
    resource: "@ApiEmployerBundle/Resources/config/routing.yml"
    prefix:   /employer-api

authentication_authorization:
    resource: "@AuthenticationAuthorizationBundle/Resources/config/routing.yml"
    prefix:   /auth

api_customer:
    resource: "@ApiCustomerBundle/Resources/config/routing.yml"
    prefix:   /customer-api

api_employee:
    resource: "@ApiEmployeeBundle/Resources/config/routing.yml"
    prefix:   /employee-api

authentication_registration:
    resource: "@AuthenticationRegistrationBundle/Resources/config/routing.yml"
    prefix:   /auth

app:
    resource: "@AppBundle/Controller/"

homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

admin:
    path:      /admin
    defaults:  { _controller: AppBundle:Default:admin }
